--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ItsGabry/NanoCombiner
branches:
- master
projects:
  NanoCombiner:
    path: ""
    libs: 
    - src: muqsit/InvMenu/InvMenu
      version: ^2.1.0
    icon: "icon.png"
...